### ISSUE TITLE
dont build on glib <2.14

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#409]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/409 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `angel_il` (@ilia-maslakov) |
> | **Keywords** | `committed-master` |

```
regex.c: In function `mc_search__regex_found_cond_one':
regex.c:261: error: `MC_SEARCH__NUM_REPL_ARGS' undeclared (first use in this function)
regex.c:261: error: (Each undeclared identifier is reported only once
regex.c:261: error: for each function it appears in.)
regex.c: In function `mc_search__cond_struct_new_init_regex':
regex.c:543: warning: passing arg 3 of `regerror' discards qualifiers from pointer target type
regex.c:545: warning: assignment discards qualifiers from pointer target type
regex.c:550: error: `MC_SEARCH__NUM_REPL_ARGS' undeclared (first use in this function)
```
<p>
Tip: [3b2707280f58b2861858c4fc45b2e88f0701d912]<br />
Start: [6ee0ed5750a8336d4fece8543559b3e62c20294d]<br />
</p>

```
git log 3b2707280^..3b2707280
```

> [!NOTE]
> Original attachments:
>
> * [ticket409.patch](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/409/ticket409.patch) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/409/ticket409.patch)) by `angel_il` (@ilia-maslakov) on <span title="2009-06-16T07:09:07+00:00">`Jun 16, 2009 at 7:09 UTC`</span>
