### ISSUE TITLE
Build error with older gcc

### ISSUE THREAD

**Issue by hgy59** [MidnightCommander/mc#4738]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
n/a
```

### Operating system

```shell
n/a
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [ ] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

when building with gcc 4.3.2, I get the compilation error:
```
  CC       editcmd.lo
editcmd.c: In function 'editcmd_check_and_create_user_syntax_directory':
editcmd.c:796: error: 'errno' undeclared (first use in this function)
editcmd.c:796: error: (Each undeclared identifier is reported only once
editcmd.c:796: error: for each function it appears in.)
editcmd.c:796: error: 'EEXIST' undeclared (first use in this function)
make[6]: *** [Makefile:527: editcmd.lo] Error 1
```

### Expected behavior

successful build

### Actual behavior

The build of `editcmd.c` fails because it is missing the include of <errno.h> (with the definition of the error codes like `EEXIST`)

### Additional context

The error was introduced by the commit 503c0af

It can simply be fixed with 
```
#include <errno.h>
```

Newer compilers do not have this problem, but it would be great if mc builds are fixed for older ones (we build mc as part of synocli-file tools for Synology NAS Devices at https://github.com/SynoCommunity/spksrc)

**Comment by zyv** [comment]
Well, adding the include wouldn't bother me, but this is such an ancient version of GCC — released almost 15 years ago! — and I can't think of a way to test it in CI. Also, it doesn't seem to make sense; even the Solaris version seems more up to date. So, these kinds of things are bound to break as we continue working on the code. Could you please confirm that the PR works for you?

**Comment by ossilator** [comment]
the more interesting question is why it works with other compilers. probably because some other (system) header includes errno.h (which would likely make it a libc, not compiler difference; maybe even some #ifdef in mc's headers). that would be clearly reliance on unspecified behavior, so adding the include is the obviously correct fix.

**Comment by zyv** [comment]
> the more interesting question is why it works with other compilers.

It's a good question, but our CI runs on Linux, macOS, Solaris, and BSD with both gcc and llvm. The problem is not visible, so to me, it's unlikely to be a compiler or libc problem.

I tried to make sense of it and did the following:


```
editor % gcc -DHAVE_CONFIG_H -I. -I../../../src/editor -I../.. -I/opt/homebrew/Cellar/glib/2.84.3/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.84.3/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.45/include -I../../.. -g -O0 -I/opt/homebrew/include -g -O0 -H -c ../../../src/editor/editcmd.c

. ../../../lib/global.h
.. /opt/homebrew/Cellar/glib/2.84.3/include/glib-2.0/glib.h
... /opt/homebrew/Cellar/glib/2.84.3/include/glib-2.0/glib/gtestutils.h
.... /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/errno.h
```
Apparently, it's glib that's pulling it in. The OP is probably using an older version of glib.

In any case, the fix seems acceptable and correct. As I said, the only annoying part is that I see no easy way to ensure that it won't break in the future.

**Comment by hgy59** [comment]
@zyv Thanks for the fix.
This was the first time I created a pre-release version of mc while working on an update to the synocli file package for Synology devices (and it was worth it).

**Comment by zyv** [comment]
@hgy59 Thank you for the report! I was waiting for your feedback before merging, but Andrew beat me to it.
