### ISSUE TITLE
doesn't compile with gcc 4.6 when using --disable-nls

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#2639]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/2639 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `ossi` (@ossilator) |

<p>
problem:<br />
</p>

```
main.c: In function 'main':
main.c:384:12: error: expected expression before ';' token
main.c:385:12: error: expected expression before ';' token
```
<p>
fix:<br />
</p>

```
--- a/lib/global.h
+++ b/lib/global.h
@@ -79,10 +79,10 @@
 #endif
 #else /* Stubs that do something close enough.  */
-#define textdomain(String)
+#define textdomain(String) 1
 #define gettext(String) (String)
 #define ngettext(String1,String2,Num) (((Num) == 1) ? (String1) : (String2))
 #define dgettext(Domain,Message) (Message)
 #define dcgettext(Domain,Message,Type) (Message)
-#define bindtextdomain(Domain,Directory)
+#define bindtextdomain(Domain,Directory) 1
 #define _(String) (String)
 #define N_(String) (String)
```
