### ISSUE TITLE
Compile failure of 4.8.1 on Snow Leopard

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#2689]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/2689 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `egmont` (@egmontkob) |

<p>
Mac OS X 10.6.8, compiling fails with<br />
</p>
<p>
[snip]<br />
</p>
<blockquote>
<p>
CC     util.o<br />
CC     selcodepage.o<br />
CCLD   mc<br />
</p>
</blockquote>
<p>
Undefined symbols:<br />
</p>
<blockquote>
<p>
"_posix_fallocate", referenced from:<br />
</p>
<blockquote>
<p>
_vfs_preallocate in libmcviewer.a(vfs.o)<br />
</p>
</blockquote>
</blockquote>
<p>
ld: symbol(s) not found<br />
collect2: ld returned 1 exit status<br />
make[3]: <strong>* [mc] Error 1<br />
make[2]: </strong>* [all-recursive] Error 1<br />
make[1]: <strong>* [all-recursive] Error 1<br />
make: </strong>* [all] Error 2<br />
$ <br />
</p>
<p>
4.8.0 compiled fine on the same system. 4.8.1 compiles fine on Linux (Ubuntu 10.04).<br />
</p>

> [!NOTE]
> Original attachments:
>
> * [mc-4.8.1-macosx-fallocate.patch](https://github.com/MidnightCommander/trac-archive/blob/master/attachments/ticket/2689/mc-4.8.1-macosx-fallocate.patch) ([raw](https://github.com/MidnightCommander/trac-archive/raw/master/attachments/ticket/2689/mc-4.8.1-macosx-fallocate.patch)) by `egmont` (@egmontkob) on <span title="2011-12-16T11:48:57+00:00">`Dec 16, 2011 at 11:48 UTC`</span>
